# Generated by Django 5.0.7 on 2024-08-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mousedata',
            options={'verbose_name': 'Mouse Data Instance', 'verbose_name_plural': 'Mouse Data Instances'},
        ),
    ]
